### ISSUE TITLE
Skip "Publish to Test PyPi" workflow when there is no change on setup.py

### ISSUE THREAD

**Issue by anapaulagomes** [anapaulagomes/pytest-picked#105]
After merging a PR from dependencies or docs updates, for instance, the workflow "Publish to Test PyPi" will be triggered and it will fail because the version on setup.py is not bumped. This workflow is nice to have because it will generate a beta version so we can test and avoid surprises when the package is published to PyPi in production. Would be nice to skip the workflow when the setup.py is not updated.

**Comment by Mastersam07** [comment]
Hello @anapaulagomes can this be assigned to me? I would send a PR

**Comment by Mastersam07** [comment]
@anapaulagomes I sent a PR on this issue...#106
