### ISSUE TITLE
Would you consider package design which enables extraction of core functionality?

### ISSUE THREAD

**Issue by fkromer** [anapaulagomes/pytest-picked#12]
I recently got interested in full-featured Test Impact Analysis in Python and I was thinking about creating a Python package [`python-tia`](https://github.com/fkromer/python-tia) which provides TIA functionality as new fun project. `pytest` is my Python test framework of choice as well. But I think TIA has a lot of potential which justifies the overhead of putting the core functionality of TIA into a separate package. This would enable integration of TIA with other test runners than `pytest`, other version control systems than `git` and probably even other coverage analysis tools than `coverage`. Are you interested in collaborating? If yes: Properly structured core functionality of `pytest-picked` could be refactored into `python-tia` leaving just the wrapping part in here...

**Comment by anapaulagomes** [comment]
Hi @fkromer, thanks for considering myself to be part of your project but at this moment I rather keep 'pytest-picked' as an independent plugin. Good luck with it!
