### ISSUE TITLE
Add support to Python 3.9+

### ISSUE THREAD

**Issue by hipertracker** [anapaulagomes/pytest-picked#143]
It does not work. No errors, no warnings, no tests running.

```
 pytest --picked

Changed test files... 0. []
Changed test folders... 0. []
Test session starts (platform: darwin, Python 3.9.10, pytest 6.2.5, pytest-sugar 0.9.4)
django: settings: dmp.settings (from ini)
rootdir: /Users/hipertracker/dev/app, configfile: pytest.ini
plugins: Faker-11.3.0, picked-0.4.6, xdist-2.5.0, forked-1.4.0, html-3.1.1, django-3.10.0, sugar-0.9.4, metadata-1.11.0, notifier-1.0.4, testmon-1.2.2
collecting ...

Results (0.01s):
```

pip freeze > requirements.lock.txt

```
...
pytest==6.2.5
pytest-django==3.10.0
pytest-forked==1.4.0
pytest-html==3.1.1
pytest-metadata==1.11.0
pytest-notifier==1.0.4
pytest-picked==0.4.6
pytest-sugar==0.9.4
pytest-testmon==1.2.2
pytest-watch==4.2.0
pytest-xdist==2.5.0
python-dateutil==2.8.2
```

```
$ python -V
Python 3.9.10
```

**Comment by anapaulagomes** [comment]
Hi. We don't support Python 3.9 yet. Please don't hesitate to add it to our [CI](https://github.com/anapaulagomes/pytest-picked/blob/dev/.github/workflows/tests.yml) and open a PR with eventual fixes.

**Comment by ksdaftari** [comment]
@anapaulagomes Are there plans to enhance to allow for higher versions of python? There is some potential I could help, what are main obstacles to getting to work for higher versions of python?

**Comment by anapaulagomes** [comment]
Hi @ksdaftari! To be honest, the code is small and I don't believe that there will be any issues. I just don't have the time to do it, unfortunately. But you are welcome to open a PR for it! 🙏🏽

**Comment by ksdaftari** [comment]
@anapaulagomes Got it, totally understand. I am looking to see if this is something wanting to integrate into my project (have large qa monorepo, so being able to on PRs smartly run files that people changed could be very useful) so if do would definitely help with this issue and perhaps help maintain.

**Comment by anapaulagomes** [comment]
Awesome! @ksdaftari
