### ISSUE TITLE
Add a way to change the default parent branch

### ISSUE THREAD

**Issue by mikicz** [anapaulagomes/pytest-picked#148]
Hi, love the package, it's super useful!

I do have one feature proposal - at my org we've migrated all our repositories to use `main` as the primary branch (as opposed to `master`), meaning that by default using `--mode=branch` doesn't work, one has to always specify `--parent-branch=main`, which gets a bit old. I would love if there was a way to permanently set the default parent branch, maybe through an environment variable or configuration in pytest.ini or similar? 

Thanks

**Comment by anapaulagomes** [comment]
Hi @mikicz! Thank you for your message and sorry for taking so long. I couldn't reply you before.

So, I totally agree. Currently, I'm taking the dust out of the project, and making `main` as the default branch will be the next issue up. :)

**Comment by anapaulagomes** [comment]
For general information: plugins' configuration can be done using the `adopts` section in pytest's configuration file. https://docs.pytest.org/en/stable/reference/customize.html
