### ISSUE TITLE
Maintainer Request

### ISSUE THREAD

**Issue by pschroeder89** [anapaulagomes/pytest-picked#160]
Hi Ana, I'd be interested in taking over as a maintainer. Thanks!

**Comment by anapaulagomes** [comment]
Hello @pschroeder89! Request accepted. :) I'm glad that is someone that already contributed to this project. I'm going to add you to the repo. Please don't hesitate to ping me if you need help with reviews and such. If you think there is a need, we can chat about a handover process too.
