### ISSUE TITLE
Run all other tests, after subset

### ISSUE THREAD

**Issue by jayvdb** [anapaulagomes/pytest-picked#18]
When running with `--cov` and 100% coverage required, picked runs only a subset of tests, and coverage fails.

Long term it would be nice to make the coverage ignore all files not modified, so the coverage percentage is of the files being tested, however relationship between files modified and test coverage will make that very difficult.

But a quick fix is to have a mode that does run all of the tests, but reorders the tests to run the guessed modified test cases first, surfacing any errors sooner in the test suite.

**Comment by anapaulagomes** [comment]
Hi @jayvdb, now (thanks to @dsalisbury )you can choose `--picked=first` to run all tests with changed tests first and then everything else. I just release a new version (https://pypi.org/project/pytest-picked/0.4.0/).
