### ISSUE TITLE
Add option to run the changed files from the current branch

### ISSUE THREAD

**Issue by anapaulagomes** [anapaulagomes/pytest-picked#2]
Let's say you are working on a feature branch and would like to run all the tests that were changed when compared with the master. To check it, you can run: `git diff --name-only master`.

Would be nice to have this option on _picked_. I'm wondering if something like `pytest --picked=branch` would be the best way to go.

**Comment by jayvdb** [comment]
I believe this would help make the plugin usable for @coala.  We want to run affected tests in CI.  That means it needs to look at the branch, or the commit, not at staged/uncommitted changes.

When I do a commit of a test atm, it shows nothing
https://travis-ci.org/jayvdb/coala/jobs/394415995

fwiw https://github.com/kstrauser/pytest-fastest allows specifying a commit to base the differences on, but unfortunately it is incompatible with pytest-cov https://github.com/kstrauser/pytest-fastest/issues/4

**Comment by anapaulagomes** [comment]
I didn't know about this project. Cool! Hoping to make it usable for your project soon.

**Comment by anapaulagomes** [comment]
@jayvdb I've pushed a draft of this feature (https://github.com/anapaulagomes/pytest-picked/pull/13). Feel free to take a look and try it out!

**Comment by anapaulagomes** [comment]
https://github.com/anapaulagomes/pytest-picked/pull/13 merged.
