### ISSUE TITLE
Module collects files with 'test' in the name, even if they are not test files.

### ISSUE THREAD

**Issue by MisterRios** [anapaulagomes/pytest-picked#4]
Hi. I was just looking through the codebase to familiarize myself with how it works, and I found this bug- It collects files that have `test` in the name, including something with `test` in the middle of the word:

 ``` 
╰─ touch sample/intestine.py 
╰─ ls sample 
__init__.py  intestine.py  __pycache__  settings.py  urls.py  wsgi.py
╰─ pytest --picked 
======================================================== test session starts =========================================================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/misterrios/Projects/sample/sample, inifile:
plugins: picked-0.1.0
collecting 0 items                                                                                                                   
Changed test files... 1. ['sample/intestine.py']
Changed test folders... 1. ['.pytest_cache/']
collected 0 items                                                                                                                    

==================================================== no tests ran in 0.05 seconds ====================================================
```

Pytest discovers tests by checking for `test_*.py` or `*_test.py`
See: https://docs.pytest.org/en/latest/goodpractices.html#test-discovery
So, a possible solution would be to use the built-in module `pathlib` to check the filenames and the file suffix combined with `startswith` and `endswith`. See: https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.name

**Comment by anapaulagomes** [comment]
Hi @MisterRios , thanks for coming up with this issue. Since we don't need to use the other features related to the path or the file (just to the name), I would consider using regex to validate it.
By the way, `pathlib` has the method `match` for it. What do you think?

In the future, would be nice to get this convention from Pytest, since [it's possible to change it](https://docs.pytest.org/en/latest/example/pythoncollection.html#changing-naming-conventions).

**Comment by anapaulagomes** [comment]
@MisterRios and @iamkhush I'm closing this issue to avoid duplicated work. I think the better way is moving to tackle #5 and get the convention from `pytest`.
