### ISSUE TITLE
Check and not assume pytest naming convention  

### ISSUE THREAD

**Issue by iamkhush** [anapaulagomes/pytest-picked#5]
As an extension to #4 , I would also suggest to get the correct pytest naming conventions ([pytest_classes](https://docs.pytest.org/en/latest/reference.html#confval-python_classes) , `pytest_function` and `pytest_files`)  and check with the correct name instead of assuming `test`

Pytest check should be accessible from the fixture - https://docs.pytest.org/en/latest/reference.html#pytestconfig

**Comment by anapaulagomes** [comment]
Maybe would be better tackling it and do it right in the first place. :)

For reference: https://docs.pytest.org/en/latest/example/pythoncollection.html#changing-naming-conventions

**Comment by MisterRios** [comment]
I agree.

Is there a way to assign the ticket to myself? Or can one of you do it for me?
Thanks.

**Comment by anapaulagomes** [comment]
It seems Github just allows to assign users that already did a contribution (I just can see Ankush and I as available options). But feel free to work on it @MisterRios ! Thanks!

**Comment by anapaulagomes** [comment]
Hi @MisterRios ! Are you still working on it? I saw that's possible to check the used file convention using `config._getini('python_files')`. Let me know if you need some help or if this issue is available for someone else.

**Comment by MisterRios** [comment]
Hi @anapaulagomes, I was working on it and hit a roadblock because of the
test_*.py settings hardwired into the parser.

I think the config that you mention here does not return the default, but
my memory is fuzzy.

I’ll take another look tonight and get back to you tomorrow.

**Comment by MisterRios** [comment]
It works! Thank you! I’ll try and finish up tonight.

**Comment by anapaulagomes** [comment]
Solved https://github.com/anapaulagomes/pytest-picked/pull/9. Thanks to @MisterRios.
